// pages/material-add/batch-entry.js
import Toast from '@vant/weapp/toast/toast';
const db = wx.cloud.database();

Page({
  data: {
    list: [],
    defaultBatchNo: '',
    defaultExpiry: '',
    showDate: false,
    currentDate: new Date().getTime(),
    minDate: new Date().getTime(),
    isScanning: false
  },

  onLoad(options) {
    // If entered with some params?
  },

  // === Scanning Logic ===
  async onScan() {
     // Prevent reentry if needed, but scanCode is modal
     wx.scanCode({
         onlyFromCamera: true,
         scanType: ['qrCode', 'barCode'],
         success: (res) => {
             this.handleScanResult(res.result);
         },
         fail: (err) => {
             if (err.errMsg && err.errMsg.indexOf('cancel') === -1) {
                 Toast.fail('识别失败');
             }
         }
     });
  },

  async handleScanResult(code) {
      if (!code) return;

      // 1. Check if already in list? (Maybe allow duplicates if different batch? But here simplified)
      // Actually duplicates might be valid for multiple physical items with same code but unique label logic?
      // Assuming code is Product Code (Generic) OR Unique Code?
      // If Product Code -> Needs to fetch Material Info
      // If Unique Code -> Already exists?
      // "Batch Entry" usually means adding NEW stock. So we scan Product Code => Add a new item of that type.
      // OR scan Unique Label of a NEW item?
      // Let's assume scanning "Product Code" (e.g., from bottle label) to add stock.

      Toast.loading('查询中...');
      try {
          // Query Material by product_code
          const res = await db.collection('materials').where({
              product_code: code
          }).get();

          if (res.data.length > 0) {
              const material = res.data[0];
              this.addItemToList(material);
              Toast.success('已添加');
               // Continuous scan?
              // wx.showModal({
              //     title: '继续扫码?',
              //     success: (m) => { if(m.confirm) this.onScan(); }
              // });
              // Better: Just toast and let user click scan again manually or auto loop?
              // Manual loop for safety.
          } else {
              // Try querying by material_name?
              // Toast.fail('未找到该料号物料');
              wx.showModal({
                  title: '未找到物料',
                  content: `系统不存在代码为 ${code} 的物料模板。是否立即新建？`,
                  confirmText: '去新建',
                  success: (res) => {
                      if (res.confirm) {
                          wx.navigateTo({
                              url: `/pages/material-add/index?product_code=${code}&tab=${this.data.activeTab || 'chemical'}`
                          });
                      }
                  }
              });
          }
      } catch (err) {
          console.error(err);
          Toast.fail('查询出错');
      }
  },

  addItemToList(material) {
      const newItem = {
          unique: Date.now() + Math.random(), // Temp ID for list
          material_id: material._id,
          material_name: material.name,
          product_code: material.product_code,
          category: material.category,
          sub_category: material.sub_category,

          // Defaults from Bulk Settings
          batch_number: this.data.defaultBatchNo || '',
          expiry_date: this.data.defaultExpiry || '',
          // For display
          expiry_date_str: this.data.defaultExpiry || '',

          quantity: {
              val: 1, // Default 1
              unit: material.unit || 'kg'
          },

          // Generate a unique code (Mock or Real?)
          // Usually generated by backend or app.
          // Let's generate a temporary unique code or leave it for backend?
          // The `batchAddInventory` function didn't generate unique_code.
          // We should generate it here.
          unique_code: this.generateUniqueCode(material.category)
      };

      this.setData({
          list: [newItem, ...this.data.list]
      });
  },

  generateUniqueCode(category) {
      const prefix = category === 'chemical' ? 'C' : 'F';
      const timestamp = Date.now().toString().slice(-6);
      const random = Math.floor(Math.random() * 1000).toString().padStart(3, '0');
      return `${prefix}${timestamp}${random}`;
  },

  // === List Management ===
  onRemoveItem(e) {
      const index = e.currentTarget.dataset.index;
      const list = this.data.list;
      list.splice(index, 1);
      this.setData({ list });
  },

  clearList() {
      wx.showModal({
          title: '确认清空',
          content: '确定要清空所有待入库项吗？',
          success: (res) => {
              if (res.confirm) {
                  this.setData({ list: [] });
              }
          }
      });
  },

  onQtyChange(e) {
      const index = e.currentTarget.dataset.index;
      const val = e.detail;
      const list = this.data.list;
      list[index].quantity.val = val;
      this.setData({ list });
  },

  // === Bulk Settings ===
  onDefaultBatchChange(e) {
      this.setData({ defaultBatchNo: e.detail });
  },

  showDatePicker() {
      this.setData({ showDate: true });
  },

  onDateClose() {
      this.setData({ showDate: false });
  },

  onDateConfirm(e) {
      const date = new Date(e.detail);
      const str = `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
      this.setData({
          defaultExpiry: str,
          showDate: false
      });
  },

  // === Submit ===
  async onSubmit() {
      if (this.data.list.length === 0) return;

      wx.showLoading({ title: '提交中...', mask: true });

      try {
          const app = getApp();
          const operator = app.globalData.user ? app.globalData.user.name : 'Unknown';

          const items = this.data.list.map(item => ({
              ...item,
              unique: undefined, // Remove temp key
              expiry_date: item.expiry_date ? new Date(item.expiry_date).toISOString() : null, // conversion
              // Ensure we pass expiry_date object or string? batchAddInventory just passes it.
              // DB stores ISO string or Date object.
              // Best to pass timestamp or ISO string.
          }));

          const res = await wx.cloud.callFunction({
              name: 'batchAddInventory',
              data: {
                  items,
                  operator_name: operator
              }
          });

          if (res.result.success) {
              wx.hideLoading();
              Toast.success(`成功入库 ${res.result.total} 项`);
              this.setData({ list: [] });

              // Navigate back or stay?
              setTimeout(() => {
                  wx.navigateBack();
              }, 1500);
          } else {
              throw new Error(res.result.msg);
          }
      } catch (err) {
          console.error(err);
          wx.hideLoading();
          Toast.fail('入库失败: ' + err.message);
      }
  }
});
